# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='あとで')),
                ('town', models.CharField(max_length=50, verbose_name='町')),
                ('prefecture', models.CharField(max_length=5, verbose_name='県名')),
                ('postal', models.CharField(max_length=10, verbose_name='郵便番号')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
    ]
