# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postalRet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='model',
            name='postal',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='model',
            name='prefecture',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='model',
            name='town',
            field=models.CharField(max_length=50),
        ),
    ]
