# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 01:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postalRet', '0002_auto_20180731_2221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Place',
        ),
    ]
